### ISSUE TITLE
Add support for dynamic selection of throttling strategies

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#1054]
**Is your feature request related to a problem?** 
Yes. PR #1053 provides support for implementing multiple "submission rate throttling" algorithms.  However, that PR requires _recompiling the code_  to accomplish switching to a different strategy.

**Feature Description**:   
Add the ability to specify the desired throttling algorithm implementation in the `contest.yaml file`, and update the `InternalController.submitJudgeRun()` method to use the specified algorithm instead of having the strategy hard-coded.

**Have you considered other ways to accomplish the same thing?** 
Could specify the algorithm in the `pc2v9.ini` file... but it seems like `contest.yaml` is more appropriate.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 
- Update the SnakeYAMLLoader to recognize `contest.yaml` entries like:
```yaml
- throttleStrategy
    name:  <some class name>
    param:  <a parameter to be passed to the named class> (e.g. an integer for the "MaxSubmissionsPerMinute" strategy)
```
- Update `InternalController` to fetch the class name from the YAML-defined properties, instantiate that class, pass it the appropriate parameters (if any), and then invoke the class when throttling is to be applied (i.e. when a submission comes from a team).

**Additional context**: 
It would be even nicer if, in addition to being able to specify the desired strategy in `contest.yaml`, the PC2 Admin had a drop-down that listed all the available strategy implementations and allowed the contest administrator to select which one should be used.
