### ISSUE TITLE
During yaml load problem custom output validator not loaded

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#407]
**Describe the issue**: 

If an output validator is specified in problem.yaml, the validator
is not loaded/used.

**To Reproduce**: 

Create the output validator file/executable.

Define a (custom) output validator in problem.yaml

validator: 
    validatorProg: 'config/bells/output_validators/bells_validator/validator'
    validatorCmd: '{:validator} {:infile} {:ansfile} {:feedbackdir} '
    usingInternal: false
    validatorOption: 0

    use-internal-validator: false
    use-clics-validator: false
    use-custom-validator: true
    use-clics-custom-validator-interface: true

Use --load to load yaml/CDP.

**Expected behavior**: 

For the problem, on the OutputValidator tab,

Selected radio: Use Custom (User-supplies) Validator
Validator program: config\bells\output_validators\bells_validator\validator
Validator Command Line: {:validator} {:infile} {:ansfile} {:feedbackdir} 
Validator interface, selected radio: Use CLICS Standard Interface

In Problem report:
   Validator name : config\bells\output_validators\bells_validator\validator

**Actual behavior**: 

For the problem, on the OutputValidator tab,

Selected radio: Use CLICS Validator

In Problem report:
   Validator name : edu.csus.ecs.pc2.validator.clicsValidator.ClicsValidator

**Environment**: 

**Log Info**:  

**Screenshots**:  

**Additional context**:

**Comment by lane55** [comment]
This bug fix meets the following requirements.
Provide a way to load a output validator program by specifying the output validator program path/name in problem.yaml.

The validator program is specified in the problem.yaml using the existing name validatorProg under
the validator group.  For example:
validator: 
    validatorProg: 'yes_always_2.sh'

There are three ways to specify the output validator program name (in this example using sumit problem short name)
There are three different ways to specify the location of an output validator:

1 - specify program name only
2 - specify a relative path channel/output_validators/yes_always_2.sh
3 - specify using absolute path 

Examples
```

# 1 - specify program name only
validator: 
    validatorProg: 'customValidatorProgram003'
# for problem sumit/ this will attempt to locate the file at 
sumit/output_validators/customValidatorProgram003

# 2 - specify a relative path channel/output_validators/yes_always_2.sh
validator: 
    validatorProg: 'sumit/output_validators/try3/customValidatorProgram003'
# for problem sumit/ this will attempt to locate the file at 
 sumit/output_validators/try3/customValidatorProgram003

# 3 - specify using absolute path 
    validatorProg: '/home/ubuntu/current/sumit/output_validators/try3/customValidatorProgram003'
# for problem sumit/ this will attempt to locate the file at 
/home/ubuntu/current/sumit/output_validators/try3/customValidatorProgram003

```
