### ISSUE TITLE
Add ability to assign/disable Permissions in Yaml

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#450]
**Is your feature request related to a problem?** 

Yes, no way to automatically (via yaml) set account permissions.

**Feature Description**: 

Add ability to set or unset any Permission for any account or set of client types using Yaml

**Have you considered other ways to accomplish the same thing?** 

Yes.  No hope.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add a new yaml section and settings.

permissions names are the class enum values: Permission.Type

General form/data.

```
permissions:
  - account: TYPE
    number: 10,11,12,13,14,15
    number: All
    enable:  list of permissions 
    disable:  list of permissions 
```

Examples

```
# disable Contest Security Alert window

  - account: ADMINISTRATOR
    number: All
    disable: VIEW_SECURITY_ALERTS

# enable EDIT_RUN for FEEDER 1
  - account: FEEDER
    number: 1
    enable: SHADOW_PROXY_TEAM, EDIT_RUN
```

**Additional context**:

**Comment by lane55** [comment]
In order to enable or disable permissions from the yaml there is a new section "permissions".
Permissions can be assigned to a number of clients or All clients in the client type.
The General form is:
```
permissions:
 - account: CLIENT_TYPE 
   number: LIST_OF_CLIENT_NUMBERS or All
   enable: LIST_OF_PERMISSIONS
   disable: LIST_OF_PERMISSIONS
```
The account client types are: ADMINISTRATOR, FEEDER JUDGE, SCOREBOARD, TEAM
The number is a list of client numbers (1,2,5,6) or All (apply permission change to all client type accounts)  All is case-insensitive.
The enable value is a list of permissions (enum names) which will be enabled/allowed
The disable value is a list of permissions (enum names) which will be dis-abled

The requirement is to apply the enabled permissions then the disable permissions for security
reasons to ensure that the disabled/disallowed permissions are not allowed.

Yaml load exceptions will throw if the client type is not valid, or there is no client number in the number list,
or if the permission (enum) name matches no permission name.
