### ISSUE TITLE
Update Admin Guide to point to Wiki article for defining/adding sites using yaml

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#499]
**Is your feature request related to a problem?** 

Missing doc in Admin PDF to describe how to add sites using yaml.

**Feature Description**: please provide a clear and concise description of the proposed feature:  

Add doc or reference in Admin PDF about the yaml used to add site definitions.

**Have you considered other ways to accomplish the same thing?** 

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

Add reference to Sites in Wiki which is:
https://github.com/pc2ccs/pc2v9/wiki/YAML-Contest-Configuration#sites-keywords

**Additional context**:

Example for defining sites

```
sites:
  - number: 1
    name: 'MainSite'
    password: site1
    IP: localhost
    port: 50002

  - number: 2
    name: 'ksas1'
    password: site2
    IP: 10.0.3.33
    port: 50002

  - number: 3
    name: 'ksas2'
    password: site3
    IP: 10.0.3.197
    port: 50002
```
